name: Update_README

on:
  push:
    branches:
      - main  # Exécutez le workflow lorsque vous poussez sur la branche principale (ou la branche de votre choix)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Utilisez la version de Python dont vous avez besoin

    - name: Install PyGithub
      run: pip install PyGithub  # Installe le module PyGithub

    - name: Run Python script
      run: python scripts/update_readme.py  # Assurez-vous que le chemin du script est correct
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README"
        git push

    - name: Complete
      run: echo "README updated"
