name: Update-README

on:
  # schedule:
  #   - cron: '*/2 * * * *' # Exécution toutes les heures
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Utilisez la version de Python dont vous avez besoin

    - name: Run Python script
      run: python scripts/generate_readme.py
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README"
        git push

    - name: Complete
      run: echo "README updated"
