name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Exécution toutes les heures

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2

      - name: Configurer Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Vous pouvez choisir une version de Node.js selon vos besoins

      - name: Installer les dépendances
        run: npm install

      - name: Exécuter le script de mise à jour du README
        run: node update-readme.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
