name: Update-README

# on:
#   schedule:
#     - cron: '*/2 * * * *' # Exécution toutes les heures

name: Update README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Compilation du script C#
        run: csc /out:scripts/update-readme.exe scripts/update-readme.cs
      
      - name: Exécuter le script C#
        run: dotnet scripts/update-readme.dll